### ISSUE TITLE
Plex on unRAID Can't Find sageplex_cfg.json

### ISSUE THREAD

**Issue by jason-bean** [ai7/sagetv-for-plexmediacenter#15]
I'm currently in the process of setting up Plex Media Server in unRAID. I have installed this successfully but it is not working. I've stopped and restarted things but alas, it just won't work.

Looking in the logs I see that it can't find the sageplex_cfg.json file. Attached is the BMT agent log.
[com.plexapp.agents.bmtagenttvshows.log.txt](https://github.com/ai7/sagetv-for-plexmediacenter/files/369503/com.plexapp.agents.bmtagenttvshows.log.txt)

**Comment by ai7** [comment]
Thank you reporting the issue. I haven't used unRAID before, so I need to familiarize myself with it and try it out....

The plugin checks several locations for the sageplex_cfg.json file, see
https://github.com/ai7/sagetv-for-plexmediacenter/blob/master/src/plex/common/sageplex/config.py#L38

It also looks at a 'SAGEPLEX_CFG' environment variable if one exists. Does it work if you explicitly set this environment variable in the unRAID environment to the absolute path to the .json file? You are seeing logs in the agent, so the scanner is able to find the cfg json file? (I recall the agent runs in a more restricted python environment than the scanner...)

**Comment by jason-bean** [comment]
Ok, that seems to have worked. In the unRAID interface I added the environment variable SAGEPLEX_CFG with the value of "/config/Library/Application Support/Plex Media Server/sageplex_cfg.json"
