### ISSUE TITLE
.Properties, .My

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ai7/sagetv-for-plexmediacenter#2]
```
Add the ability for the SageTVBMTAgent.py to utilize the .properties and .my 
files created by SageTV and updated by BMT.

IF we can use these files to obtain the majority of information about the media 
file, then we can limit the number of SageTV BMT calls via the sagexapis.
```

Original issue reported on code.google.com by `Mreid910` on 6 Jan 2012 at 3:00

**Comment by ai7** [comment]
Closing as not needed as it is better to query sagex rather than parsing the .properties file directly in case the implementation changes. Also the call is pretty fast now.
