### ISSUE TITLE
Plex Ap

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ai7/sagetv-for-plexmediacenter#7]
```
Research plugin.  Can we bundle the scanner and agent as a plugin and make it 
available on the plex aps?


```

Original issue reported on code.google.com by `Mreid910` on 6 Jan 2012 at 3:12

**Comment by ai7** [comment]
The link is no valid anymore. The current terminology may be Channel.

Not sure if we want to go this route. Closing this for now. Will re-open if we want to explorer this.
