### ISSUE TITLE
When episodeTitle is blank,  set the episodeTitle to AiringStartTime

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ai7/sagetv-for-plexmediacenter#9]
```
In sageTVScanner.py,  when the episodeTitle is blank,  the episodeTitle is to 
the showTitle with the following code:

if( episodeTitle == None or episodeTitle == ""):
    episodeTitle = showTitle

This makes Plex clients (such as roku or ipad) list shows such as "NBC Nightly 
News", which don't have episodeTitles in a way that is imposible to figure 
which airing is which.  It will show something like this:

"Episode 14028: NBC Nightly News"

Since the episode number is also meaningless, this makes it impossible to 
distinguish which "episode" is which.

Instead,  if you set the episodeTitle to the AiringStartTime like this:

if( episodeTitle == None or episodeTitle == ""):
    episodeTitle = date.fromtimestamp(recordTime).isoformat() 

The Plex clients will display:

"Episode 14028: 2012-05-26"

Much more useful!

Attached is the modified code I am currently using.  There might be more 
elegant way to format the date than isoformat(),  I am just not a python coder, 
 so this was a quick and dirty.

```

Original issue reported on code.google.com by `a...@vandeputte.us` on 1 Jun 2012 at 2:44

Attachments:
* [SageTV Scanner.py](https://storage.googleapis.com/google-code-attachments/sagetv-for-plexmediacenter/issue-9/comment-0/SageTV Scanner.py)

**Comment by ai7** [comment]
I have just fixed the issue in a slightly different way.

The code was using the AiringID as the episode number if one is not available. This is an internal SageTV number and not very meaningful.

The new code will extract the episode number from the ShowExternalID field (program-id). This is typically the last 4 character of the program-id, representing the episode number of the entire show, regardless of season.

If this number is all 0 (possible for certain shows that begins with SH...), then it will set a YYYYMMDD as the episode number, with the timestamp coming from original-airing-date, recording-time, and current date, whichever is available.

I think this should fix the issue. The new 8.1.0 download contains the new code.

Closing issue.
